extends Node

enum CROP_STAGES {SAPLING, CROSSBREEDING, MATURING, FRUITING, RIPE, DYING, DEAD}
const DEHYDRATION_STAGE_LENGTH_FACTOR := 2
const EXTREME_DEHYDRATION_STAGE_LENGTH_FACTOR := 4
const TILE_SIZE := 16
